global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'prometheus:9090' ]
  - job_name: 'angular-observability'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'collector:9464' ]
  - job_name: 'spring-observability-opentelemetry'
    scrape_interval: 5s
    metrics_path: 'actuator/prometheus'
    static_configs:
      - targets: [ 'spring-observability-opentelemetry:9080' ]
  - job_name: 'spring-observability-opentracing'
    scrape_interval: 5s
    metrics_path: 'actuator/prometheus'
    static_configs:
      - targets: [ 'spring-observability-opentracing:9081' ]